//
//  WordEntry.swift
//  Pantomime Bazi
//
//  Created by Erfan Yarahmadi on 01/04/2026.
//
//
//

import Foundation

struct WordEntry: Identifiable {
    let id: UUID
    let text: String
    let category: WordCategory
    let points: Int
    let isCustom: Bool

    init(_ text: String, category: WordCategory, points: Int) {
        self.id = UUID()
        self.text = text
        self.category = category
        self.points = points
        self.isCustom = false
    }

    init(customText: String) {
        self.id = UUID()
        self.text = customText
        self.category = .everyday
        self.points = 9
        self.isCustom = true
    }

    func displayText(language: AppLanguage) -> String { text }
    var _english: String { text }
    var _persian: String { text }
}

enum AppLanguage: String, CaseIterable {
    case english = "EN"
    case persian = "FA"
    var isRTL: Bool { self == .persian }
    var flagEmoji: String { self == .english ? "🇺🇸" : "🇮🇷" }
    var label: String { self == .english ? "EN" : "فا" }
}

enum WordCategory: String, CaseIterable, Identifiable {
    case animals = "Animals"
    case actions = "Actions"
    case professions = "Professions"
    case movies = "Movies & TV"
    case food = "Food"
    case sports = "Sports"
    case everyday = "Everyday Life"
    case nature = "Nature"
    case emotions = "Emotions"
    case famous = "Famous People"
    case music = "Music"
    case places = "Places"
    var id: String { rawValue }
    var persianName: String {
        switch self {
        case .animals: return "حیوانات"
        case .actions: return "حرکات"
        case .professions: return "مشاغل"
        case .movies: return "فیلم و سریال"
        case .food: return "غذا"
        case .sports: return "ورزش"
        case .everyday: return "زندگی روزمره"
        case .nature: return "طبیعت"
        case .emotions: return "احساسات"
        case .famous: return "افراد مشهور"
        case .music: return "موسیقی"
        case .places: return "مکان‌ها"
        }
    }
    var emoji: String {
        switch self {
        case .animals: return "🐾"
        case .actions: return "🏃"
        case .professions: return "👩‍💼"
        case .movies: return "🎬"
        case .food: return "🍕"
        case .sports: return "⚽"
        case .everyday: return "🏠"
        case .nature: return "🌿"
        case .emotions: return "😄"
        case .famous: return "⭐"
        case .music: return "🎵"
        case .places: return "🗺️"
        }
    }
}

func wordDatabase(for language: AppLanguage) -> [WordEntry] {
    language == .persian ? persianWordDatabase : englishWordDatabase
}

// MARK: - PERSIAN DATABASE
let persianWordDatabase: [WordEntry] = [
    // حیوانات
    WordEntry("پنگوئن", category: .animals, points: 3),
    WordEntry("فیل", category: .animals, points: 3),
    WordEntry("میمون", category: .animals, points: 3),
    WordEntry("اردک", category: .animals, points: 3),
    WordEntry("خرس", category: .animals, points: 3),
    WordEntry("شیر", category: .animals, points: 3),
    WordEntry("قورباغه", category: .animals, points: 3),
    WordEntry("گربه", category: .animals, points: 3),
    WordEntry("سگ", category: .animals, points: 3),
    WordEntry("خروس", category: .animals, points: 3),
    WordEntry("کانگارو", category: .animals, points: 5),
    WordEntry("تمساح", category: .animals, points: 5),
    WordEntry("زرافه", category: .animals, points: 5),
    WordEntry("طوطی", category: .animals, points: 5),
    WordEntry("دلفین", category: .animals, points: 5),
    WordEntry("طاووس", category: .animals, points: 5),
    WordEntry("شتر", category: .animals, points: 5),
    WordEntry("پاندا", category: .animals, points: 5),
    WordEntry("اسب", category: .animals, points: 5),
    WordEntry("فلامینگو", category: .animals, points: 5),
    WordEntry("خرچنگ", category: .animals, points: 7),
    WordEntry("عنکبوت", category: .animals, points: 7),
    WordEntry("گوریل", category: .animals, points: 7),
    WordEntry("مار", category: .animals, points: 7),
    WordEntry("آفتاب‌پرست", category: .animals, points: 7),
    WordEntry("تنبل‌خرس", category: .animals, points: 7),
    WordEntry("خفاش", category: .animals, points: 7),
    WordEntry("اختاپوس", category: .animals, points: 7),
    WordEntry("کرگدن", category: .animals, points: 7),
    WordEntry("گراز", category: .animals, points: 7),
    // حرکات
    WordEntry("خوابیدن", category: .actions, points: 3),
    WordEntry("گریه کردن", category: .actions, points: 3),
    WordEntry("دویدن", category: .actions, points: 3),
    WordEntry("رقصیدن", category: .actions, points: 3),
    WordEntry("شنا کردن", category: .actions, points: 3),
    WordEntry("خمیازه کشیدن", category: .actions, points: 3),
    WordEntry("عطسه کردن", category: .actions, points: 3),
    WordEntry("غذا خوردن", category: .actions, points: 3),
    WordEntry("پریدن", category: .actions, points: 3),
    WordEntry("خندیدن", category: .actions, points: 3),
    WordEntry("آشپزی کردن", category: .actions, points: 5),
    WordEntry("رانندگی کردن", category: .actions, points: 5),
    WordEntry("نقاشی کردن", category: .actions, points: 5),
    WordEntry("نماز خواندن", category: .actions, points: 5),
    WordEntry("اتو کردن لباس", category: .actions, points: 5),
    WordEntry("مسواک زدن", category: .actions, points: 5),
    WordEntry("سلفی گرفتن", category: .actions, points: 5),
    WordEntry("بافتن", category: .actions, points: 5),
    WordEntry("باغبانی کردن", category: .actions, points: 5),
    WordEntry("نقاشی دیواری", category: .actions, points: 5),
    WordEntry("بندبازی", category: .actions, points: 7),
    WordEntry("جیب‌بری", category: .actions, points: 7),
    WordEntry("پلی‌بک خواندن", category: .actions, points: 7),
    WordEntry("خوابگردی", category: .actions, points: 7),
    WordEntry("شعبده‌بازی", category: .actions, points: 7),
    WordEntry("غواصی", category: .actions, points: 7),
    WordEntry("پارکور", category: .actions, points: 7),
    WordEntry("آتش‌بازی", category: .actions, points: 7),
    WordEntry("دست‌فروشی", category: .actions, points: 7),
    WordEntry("چرت زدن سر کلاس", category: .actions, points: 7),
    // مشاغل
    WordEntry("دکتر", category: .professions, points: 3),
    WordEntry("معلم", category: .professions, points: 3),
    WordEntry("آشپز", category: .professions, points: 3),
    WordEntry("آتش‌نشان", category: .professions, points: 3),
    WordEntry("پلیس", category: .professions, points: 3),
    WordEntry("کشاورز", category: .professions, points: 3),
    WordEntry("خلبان", category: .professions, points: 3),
    WordEntry("دندانپزشک", category: .professions, points: 3),
    WordEntry("آرایشگر", category: .professions, points: 3),
    WordEntry("نانوا", category: .professions, points: 3),
    WordEntry("جراح", category: .professions, points: 5),
    WordEntry("فضانورد", category: .professions, points: 5),
    WordEntry("شعبده‌باز", category: .professions, points: 5),
    WordEntry("نجات‌غریق", category: .professions, points: 5),
    WordEntry("خبرنگار", category: .professions, points: 5),
    WordEntry("کشتی‌گیر", category: .professions, points: 5),
    WordEntry("راننده تاکسی", category: .professions, points: 5),
    WordEntry("لوله‌کش", category: .professions, points: 5),
    WordEntry("سرایدار", category: .professions, points: 5),
    WordEntry("دلال", category: .professions, points: 5),
    WordEntry("پانتومیمیست", category: .professions, points: 7),
    WordEntry("باستان‌شناس", category: .professions, points: 7),
    WordEntry("عروسک‌گردان", category: .professions, points: 7),
    WordEntry("بدن‌نرم", category: .professions, points: 7),
    WordEntry("جارچی", category: .professions, points: 7),
    WordEntry("تعزیه‌خوان", category: .professions, points: 7),
    WordEntry("دوره‌گرد", category: .professions, points: 7),
    WordEntry("نقال", category: .professions, points: 7),
    WordEntry("مداح", category: .professions, points: 7),
    WordEntry("قصاب", category: .professions, points: 7),
    // فیلم و سریال
    WordEntry("تایتانیک", category: .movies, points: 3),
    WordEntry("تام و جری", category: .movies, points: 3),
    WordEntry("مرد عنکبوتی", category: .movies, points: 3),
    WordEntry("تنها در خانه", category: .movies, points: 3),
    WordEntry("شرک", category: .movies, points: 3),
    WordEntry("در جستجوی نمو", category: .movies, points: 3),
    WordEntry("ماسک", category: .movies, points: 3),
    WordEntry("هری پاتر", category: .movies, points: 3),
    WordEntry("شیرشاه", category: .movies, points: 3),
    WordEntry("پینوکیو", category: .movies, points: 3),
    WordEntry("ماتریکس", category: .movies, points: 5),
    WordEntry("جوکر", category: .movies, points: 5),
    WordEntry("بازی مرکب", category: .movies, points: 5),
    WordEntry("بازی تاج و تخت", category: .movies, points: 5),
    WordEntry("پدرخوانده", category: .movies, points: 5),
    WordEntry("داستان اسباب‌بازی", category: .movies, points: 5),
    WordEntry("انتقام‌جویان", category: .movies, points: 5),
    WordEntry("انگل", category: .movies, points: 5),
    WordEntry("جدایی نادر از سیمین", category: .movies, points: 5),
    WordEntry("اجاره‌نشین‌ها", category: .movies, points: 5),
    WordEntry("تلقین", category: .movies, points: 7),
    WordEntry("فهرست شیندلر", category: .movies, points: 7),
    WordEntry("نمایش ترومن", category: .movies, points: 7),
    WordEntry("فارست گامپ", category: .movies, points: 7),
    WordEntry("باشگاه مشت‌زنی", category: .movies, points: 7),
    WordEntry("شوالیه تاریکی", category: .movies, points: 7),
    WordEntry("مادر", category: .movies, points: 7),
    WordEntry("درباره الی", category: .movies, points: 7),
    WordEntry("چ", category: .movies, points: 7),
    WordEntry("ابد و یک روز", category: .movies, points: 7),
    // غذا
    WordEntry("کباب", category: .food, points: 3),
    WordEntry("برنج", category: .food, points: 3),
    WordEntry("نان", category: .food, points: 3),
    WordEntry("هندوانه", category: .food, points: 3),
    WordEntry("آبگوشت", category: .food, points: 3),
    WordEntry("پیتزا", category: .food, points: 3),
    WordEntry("بستنی", category: .food, points: 3),
    WordEntry("ساندویچ", category: .food, points: 3),
    WordEntry("چای", category: .food, points: 3),
    WordEntry("نان سنگک", category: .food, points: 3),
    WordEntry("قورمه سبزی", category: .food, points: 5),
    WordEntry("فسنجان", category: .food, points: 5),
    WordEntry("ته‌دیگ", category: .food, points: 5),
    WordEntry("آش رشته", category: .food, points: 5),
    WordEntry("خورش بادمجان", category: .food, points: 5),
    WordEntry("کوکو سبزی", category: .food, points: 5),
    WordEntry("دلمه", category: .food, points: 5),
    WordEntry("میرزاقاسمی", category: .food, points: 5),
    WordEntry("ماست موسیر", category: .food, points: 5),
    WordEntry("پشمک", category: .food, points: 5),
    WordEntry("آلبالو پلو", category: .food, points: 7),
    WordEntry("قیمه نثار", category: .food, points: 7),
    WordEntry("زرشک پلو با مرغ", category: .food, points: 7),
    WordEntry("کله‌پاچه", category: .food, points: 7),
    WordEntry("سیراب شیردان", category: .food, points: 7),
    WordEntry("رشته پلو", category: .food, points: 7),
    WordEntry("بریانی اصفهانی", category: .food, points: 7),
    WordEntry("حلیم", category: .food, points: 7),
    WordEntry("مرصع پلو", category: .food, points: 7),
    WordEntry("لواشک", category: .food, points: 7),
    // ورزش
    WordEntry("فوتبال", category: .sports, points: 3),
    WordEntry("بسکتبال", category: .sports, points: 3),
    WordEntry("شنا", category: .sports, points: 3),
    WordEntry("تنیس", category: .sports, points: 3),
    WordEntry("بوکس", category: .sports, points: 3),
    WordEntry("والیبال", category: .sports, points: 3),
    WordEntry("دویدن", category: .sports, points: 3),
    WordEntry("دوچرخه‌سواری", category: .sports, points: 3),
    WordEntry("اسکی", category: .sports, points: 3),
    WordEntry("کشتی", category: .sports, points: 3),
    WordEntry("تیراندازی با کمان", category: .sports, points: 5),
    WordEntry("وزنه‌برداری", category: .sports, points: 5),
    WordEntry("اسب‌سواری", category: .sports, points: 5),
    WordEntry("کاراته", category: .sports, points: 5),
    WordEntry("ژیمناستیک", category: .sports, points: 5),
    WordEntry("موج‌سواری", category: .sports, points: 5),
    WordEntry("چوگان", category: .sports, points: 5),
    WordEntry("شمشیربازی", category: .sports, points: 5),
    WordEntry("پینگ‌پنگ", category: .sports, points: 5),
    WordEntry("کبدی", category: .sports, points: 5),
    WordEntry("پارکور", category: .sports, points: 7),
    WordEntry("شنای همگام", category: .sports, points: 7),
    WordEntry("ژیمناستیک ریتمیک", category: .sports, points: 7),
    WordEntry("پرتاب نیزه", category: .sports, points: 7),
    WordEntry("ورزش باستانی", category: .sports, points: 7),
    WordEntry("زورخانه", category: .sports, points: 7),
    WordEntry("چوب‌بازی", category: .sports, points: 7),
    WordEntry("الک‌دولک", category: .sports, points: 7),
    WordEntry("گرگم به هوا", category: .sports, points: 7),
    WordEntry("پنج‌گانه مدرن", category: .sports, points: 7),
    // زندگی روزمره
    WordEntry("عروسی", category: .everyday, points: 3),
    WordEntry("بیمارستان", category: .everyday, points: 3),
    WordEntry("فرودگاه", category: .everyday, points: 3),
    WordEntry("سوپرمارکت", category: .everyday, points: 3),
    WordEntry("ترافیک", category: .everyday, points: 3),
    WordEntry("جشن تولد", category: .everyday, points: 3),
    WordEntry("ساعت زنگ‌دار", category: .everyday, points: 3),
    WordEntry("آسانسور", category: .everyday, points: 3),
    WordEntry("صف", category: .everyday, points: 3),
    WordEntry("بازار", category: .everyday, points: 3),
    WordEntry("اسباب‌کشی", category: .everyday, points: 5),
    WordEntry("قطع برق", category: .everyday, points: 5),
    WordEntry("پارکینگ", category: .everyday, points: 5),
    WordEntry("لباسشویی", category: .everyday, points: 5),
    WordEntry("مصاحبه کاری", category: .everyday, points: 5),
    WordEntry("جشن غافلگیری", category: .everyday, points: 5),
    WordEntry("خرید آنلاین", category: .everyday, points: 5),
    WordEntry("شب یلدا", category: .everyday, points: 5),
    WordEntry("چهارشنبه‌سوری", category: .everyday, points: 5),
    WordEntry("عید نوروز", category: .everyday, points: 5),
    WordEntry("گیر کردن در آسانسور", category: .everyday, points: 7),
    WordEntry("سخنرانی عمومی", category: .everyday, points: 7),
    WordEntry("اشتباه تصحیح خودکار", category: .everyday, points: 7),
    WordEntry("بحران میانسالی", category: .everyday, points: 7),
    WordEntry("سکوت ناخوشایند", category: .everyday, points: 7),
    WordEntry("دیر رسیدن به مهمانی", category: .everyday, points: 7),
    WordEntry("گم کردن گوشی", category: .everyday, points: 7),
    WordEntry("دعوای فامیلی سر سفره", category: .everyday, points: 7),
    WordEntry("شب امتحان", category: .everyday, points: 7),
    WordEntry("قطع شدن اینترنت", category: .everyday, points: 7),
    // طبیعت
    WordEntry("رنگین‌کمان", category: .nature, points: 3),
    WordEntry("غروب آفتاب", category: .nature, points: 3),
    WordEntry("بیابان", category: .nature, points: 3),
    WordEntry("جنگل", category: .nature, points: 3),
    WordEntry("اقیانوس", category: .nature, points: 3),
    WordEntry("کوه", category: .nature, points: 3),
    WordEntry("رودخانه", category: .nature, points: 3),
    WordEntry("آبشار", category: .nature, points: 3),
    WordEntry("برف", category: .nature, points: 3),
    WordEntry("باد", category: .nature, points: 3),
    WordEntry("گردباد", category: .nature, points: 5),
    WordEntry("کولاک", category: .nature, points: 5),
    WordEntry("صاعقه", category: .nature, points: 5),
    WordEntry("واحه", category: .nature, points: 5),
    WordEntry("شفق قطبی", category: .nature, points: 5),
    WordEntry("صخره مرجانی", category: .nature, points: 5),
    WordEntry("خسوف", category: .nature, points: 5),
    WordEntry("سیل", category: .nature, points: 5),
    WordEntry("مه", category: .nature, points: 5),
    WordEntry("طوفان شن", category: .nature, points: 5),
    WordEntry("زلزله", category: .nature, points: 7),
    WordEntry("آتشفشان", category: .nature, points: 7),
    WordEntry("بهمن", category: .nature, points: 7),
    WordEntry("یخچال طبیعی", category: .nature, points: 7),
    WordEntry("جزر و مد", category: .nature, points: 7),
    WordEntry("سیاهچاله", category: .nature, points: 7),
    WordEntry("خشکسالی", category: .nature, points: 7),
    WordEntry("نور زیستی", category: .nature, points: 7),
    WordEntry("شعله خورشیدی", category: .nature, points: 7),
    WordEntry("رانش زمین", category: .nature, points: 7),
    // احساسات
    WordEntry("شادی", category: .emotions, points: 3),
    WordEntry("ترس", category: .emotions, points: 3),
    WordEntry("عصبانیت", category: .emotions, points: 3),
    WordEntry("غم", category: .emotions, points: 3),
    WordEntry("تعجب", category: .emotions, points: 3),
    WordEntry("عشق", category: .emotions, points: 3),
    WordEntry("انزجار", category: .emotions, points: 3),
    WordEntry("سردرگمی", category: .emotions, points: 3),
    WordEntry("هیجان", category: .emotions, points: 3),
    WordEntry("غرور", category: .emotions, points: 3),
    WordEntry("حسادت", category: .emotions, points: 5),
    WordEntry("خجالت", category: .emotions, points: 5),
    WordEntry("حوصله‌سر رفتن", category: .emotions, points: 5),
    WordEntry("دلتنگی", category: .emotions, points: 5),
    WordEntry("تنهایی", category: .emotions, points: 5),
    WordEntry("آسودگی", category: .emotions, points: 5),
    WordEntry("احساس گناه", category: .emotions, points: 5),
    WordEntry("اضطراب", category: .emotions, points: 5),
    WordEntry("رشک", category: .emotions, points: 5),
    WordEntry("سپاسگزاری", category: .emotions, points: 5),
    WordEntry("مالیخولیا", category: .emotions, points: 7),
    WordEntry("شگفتی", category: .emotions, points: 7),
    WordEntry("یأس", category: .emotions, points: 7),
    WordEntry("سرخوشی", category: .emotions, points: 7),
    WordEntry("خیانت", category: .emotions, points: 7),
    WordEntry("انتظار", category: .emotions, points: 7),
    WordEntry("دلتنگی خانه", category: .emotions, points: 7),
    WordEntry("دل شکستگی", category: .emotions, points: 7),
    WordEntry("آرامش", category: .emotions, points: 7),
    WordEntry("حسرت", category: .emotions, points: 7),
    // افراد مشهور
    WordEntry("چارلی چاپلین", category: .famous, points: 3),
    WordEntry("مایکل جکسون", category: .famous, points: 3),
    WordEntry("کریستیانو رونالدو", category: .famous, points: 3),
    WordEntry("بابانوئل", category: .famous, points: 3),
    WordEntry("سوپرمن", category: .famous, points: 3),
    WordEntry("دراکولا", category: .famous, points: 3),
    WordEntry("بتمن", category: .famous, points: 3),
    WordEntry("شرلوک هولمز", category: .famous, points: 3),
    WordEntry("انیشتین", category: .famous, points: 3),
    WordEntry("ناپلئون", category: .famous, points: 3),
    WordEntry("کلئوپاترا", category: .famous, points: 5),
    WordEntry("بیانسه", category: .famous, points: 5),
    WordEntry("بروس لی", category: .famous, points: 5),
    WordEntry("فردی مرکوری", category: .famous, points: 5),
    WordEntry("محمد علی", category: .famous, points: 5),
    WordEntry("مریلین مونرو", category: .famous, points: 5),
    WordEntry("جیمز باند", category: .famous, points: 5),
    WordEntry("استیو جابز", category: .famous, points: 5),
    WordEntry("چنگیز خان", category: .famous, points: 5),
    WordEntry("حافظ", category: .famous, points: 5),
    WordEntry("ایلان ماسک", category: .famous, points: 7),
    WordEntry("لئوناردو داوینچی", category: .famous, points: 7),
    WordEntry("اوپرا وینفری", category: .famous, points: 7),
    WordEntry("شکسپیر", category: .famous, points: 7),
    WordEntry("نیکولا تسلا", category: .famous, points: 7),
    WordEntry("مهاتما گاندی", category: .famous, points: 7),
    WordEntry("ماری کوری", category: .famous, points: 7),
    WordEntry("پیکاسو", category: .famous, points: 7),
    WordEntry("رودکی", category: .famous, points: 7),
    WordEntry("ابن سینا", category: .famous, points: 7),
    // موسیقی
    WordEntry("آواز خواندن", category: .music, points: 3),
    WordEntry("طبل", category: .music, points: 3),
    WordEntry("پیانو", category: .music, points: 3),
    WordEntry("گیتار", category: .music, points: 3),
    WordEntry("ویولن", category: .music, points: 3),
    WordEntry("هدفون", category: .music, points: 3),
    WordEntry("کنسرت", category: .music, points: 3),
    WordEntry("میکروفون", category: .music, points: 3),
    WordEntry("رقص", category: .music, points: 3),
    WordEntry("دی‌جی", category: .music, points: 3),
    WordEntry("کارائوکه", category: .music, points: 5),
    WordEntry("موزیک ویدیو", category: .music, points: 5),
    WordEntry("گروه کر", category: .music, points: 5),
    WordEntry("مسابقه رپ", category: .music, points: 5),
    WordEntry("نوازندگی خیابانی", category: .music, points: 5),
    WordEntry("گرامافون", category: .music, points: 5),
    WordEntry("گیتار هوایی", category: .music, points: 5),
    WordEntry("فلش‌ماب", category: .music, points: 5),
    WordEntry("تصنیف", category: .music, points: 5),
    WordEntry("دف زدن", category: .music, points: 5),
    WordEntry("رهبری ارکستر", category: .music, points: 7),
    WordEntry("بیت‌باکسینگ", category: .music, points: 7),
    WordEntry("نی نواختن", category: .music, points: 7),
    WordEntry("تار نواختن", category: .music, points: 7),
    WordEntry("سنتور نواختن", category: .music, points: 7),
    WordEntry("اپرا خواندن", category: .music, points: 7),
    WordEntry("آواز گلویی", category: .music, points: 7),
    WordEntry("تنبک نواختن", category: .music, points: 7),
    WordEntry("کمانچه نواختن", category: .music, points: 7),
    WordEntry("سه‌تار نواختن", category: .music, points: 7),
    // مکان‌ها
    WordEntry("ساحل", category: .places, points: 3),
    WordEntry("کتابخانه", category: .places, points: 3),
    WordEntry("رستوران", category: .places, points: 3),
    WordEntry("باغ وحش", category: .places, points: 3),
    WordEntry("موزه", category: .places, points: 3),
    WordEntry("سینما", category: .places, points: 3),
    WordEntry("پارک", category: .places, points: 3),
    WordEntry("مسجد", category: .places, points: 3),
    WordEntry("باشگاه", category: .places, points: 3),
    WordEntry("بازار", category: .places, points: 3),
    WordEntry("شهر بازی", category: .places, points: 5),
    WordEntry("پیست یخ", category: .places, points: 5),
    WordEntry("ایستگاه فضایی", category: .places, points: 5),
    WordEntry("خانه ارواح", category: .places, points: 5),
    WordEntry("بازار بزرگ تهران", category: .places, points: 5),
    WordEntry("سونا", category: .places, points: 5),
    WordEntry("زندان", category: .places, points: 5),
    WordEntry("کاخ گلستان", category: .places, points: 5),
    WordEntry("میدان نقش جهان", category: .places, points: 5),
    WordEntry("پاساژ", category: .places, points: 5),
    WordEntry("برج آزادی", category: .places, points: 7),
    WordEntry("تخت جمشید", category: .places, points: 7),
    WordEntry("مثلث برمودا", category: .places, points: 7),
    WordEntry("منطقه ۵۱", category: .places, points: 7),
    WordEntry("کولوسئوم", category: .places, points: 7),
    WordEntry("آلکاتراز", category: .places, points: 7),
    WordEntry("زیردریایی", category: .places, points: 7),
    WordEntry("چرنوبیل", category: .places, points: 7),
    WordEntry("برج بابل", category: .places, points: 7),
    WordEntry("باغ ایرانی", category: .places, points: 7),
]

// MARK: - ENGLISH DATABASE
let englishWordDatabase: [WordEntry] = [
    // Animals
    WordEntry("Penguin", category: .animals, points: 3),
    WordEntry("Elephant", category: .animals, points: 3),
    WordEntry("Monkey", category: .animals, points: 3),
    WordEntry("Duck", category: .animals, points: 3),
    WordEntry("Bear", category: .animals, points: 3),
    WordEntry("Lion", category: .animals, points: 3),
    WordEntry("Frog", category: .animals, points: 3),
    WordEntry("Butterfly", category: .animals, points: 3),
    WordEntry("Cat", category: .animals, points: 3),
    WordEntry("Dog", category: .animals, points: 3),
    WordEntry("Kangaroo", category: .animals, points: 5),
    WordEntry("Flamingo", category: .animals, points: 5),
    WordEntry("Crocodile", category: .animals, points: 5),
    WordEntry("Giraffe", category: .animals, points: 5),
    WordEntry("Parrot", category: .animals, points: 5),
    WordEntry("Dolphin", category: .animals, points: 5),
    WordEntry("Peacock", category: .animals, points: 5),
    WordEntry("Camel", category: .animals, points: 5),
    WordEntry("Panda", category: .animals, points: 5),
    WordEntry("Gorilla", category: .animals, points: 5),
    WordEntry("Crab", category: .animals, points: 7),
    WordEntry("Spider", category: .animals, points: 7),
    WordEntry("Snake", category: .animals, points: 7),
    WordEntry("Chameleon", category: .animals, points: 7),
    WordEntry("Platypus", category: .animals, points: 7),
    WordEntry("Sloth", category: .animals, points: 7),
    WordEntry("Manta ray", category: .animals, points: 7),
    WordEntry("Polar bear", category: .animals, points: 7),
    WordEntry("Octopus", category: .animals, points: 7),
    WordEntry("Rhinoceros", category: .animals, points: 7),
    // Actions
    WordEntry("Sleeping", category: .actions, points: 3),
    WordEntry("Crying", category: .actions, points: 3),
    WordEntry("Running", category: .actions, points: 3),
    WordEntry("Dancing", category: .actions, points: 3),
    WordEntry("Swimming", category: .actions, points: 3),
    WordEntry("Yawning", category: .actions, points: 3),
    WordEntry("Sneezing", category: .actions, points: 3),
    WordEntry("Eating", category: .actions, points: 3),
    WordEntry("Jumping", category: .actions, points: 3),
    WordEntry("Laughing", category: .actions, points: 3),
    WordEntry("Cooking", category: .actions, points: 5),
    WordEntry("Driving", category: .actions, points: 5),
    WordEntry("Painting", category: .actions, points: 5),
    WordEntry("Ironing clothes", category: .actions, points: 5),
    WordEntry("Brushing teeth", category: .actions, points: 5),
    WordEntry("Taking selfie", category: .actions, points: 5),
    WordEntry("Knitting", category: .actions, points: 5),
    WordEntry("Rock climbing", category: .actions, points: 5),
    WordEntry("Meditating", category: .actions, points: 5),
    WordEntry("Gardening", category: .actions, points: 5),
    WordEntry("Tightrope walking", category: .actions, points: 7),
    WordEntry("Sword swallowing", category: .actions, points: 7),
    WordEntry("Pickpocketing", category: .actions, points: 7),
    WordEntry("Lip syncing", category: .actions, points: 7),
    WordEntry("Sleepwalking", category: .actions, points: 7),
    WordEntry("Scuba diving", category: .actions, points: 7),
    WordEntry("Parkour", category: .actions, points: 7),
    WordEntry("Fire eating", category: .actions, points: 7),
    WordEntry("Ventriloquism", category: .actions, points: 7),
    WordEntry("Speed reading", category: .actions, points: 7),
    // Professions
    WordEntry("Doctor", category: .professions, points: 3),
    WordEntry("Teacher", category: .professions, points: 3),
    WordEntry("Chef", category: .professions, points: 3),
    WordEntry("Firefighter", category: .professions, points: 3),
    WordEntry("Police", category: .professions, points: 3),
    WordEntry("Farmer", category: .professions, points: 3),
    WordEntry("Pilot", category: .professions, points: 3),
    WordEntry("Dentist", category: .professions, points: 3),
    WordEntry("Barber", category: .professions, points: 3),
    WordEntry("Baker", category: .professions, points: 3),
    WordEntry("Surgeon", category: .professions, points: 5),
    WordEntry("Astronaut", category: .professions, points: 5),
    WordEntry("Magician", category: .professions, points: 5),
    WordEntry("Lifeguard", category: .professions, points: 5),
    WordEntry("Journalist", category: .professions, points: 5),
    WordEntry("Wrestler", category: .professions, points: 5),
    WordEntry("Taxi driver", category: .professions, points: 5),
    WordEntry("Plumber", category: .professions, points: 5),
    WordEntry("Janitor", category: .professions, points: 5),
    WordEntry("Hairdresser", category: .professions, points: 5),
    WordEntry("Mime artist", category: .professions, points: 7),
    WordEntry("Archaeologist", category: .professions, points: 7),
    WordEntry("Puppeteer", category: .professions, points: 7),
    WordEntry("Contortionist", category: .professions, points: 7),
    WordEntry("Town crier", category: .professions, points: 7),
    WordEntry("Auctioneer", category: .professions, points: 7),
    WordEntry("Locksmith", category: .professions, points: 7),
    WordEntry("Taxidermist", category: .professions, points: 7),
    WordEntry("Cartographer", category: .professions, points: 7),
    WordEntry("Sommelier", category: .professions, points: 7),
    // Movies & TV
    WordEntry("Titanic", category: .movies, points: 3),
    WordEntry("The Lion King", category: .movies, points: 3),
    WordEntry("Harry Potter", category: .movies, points: 3),
    WordEntry("Tom and Jerry", category: .movies, points: 3),
    WordEntry("Spider-Man", category: .movies, points: 3),
    WordEntry("Home Alone", category: .movies, points: 3),
    WordEntry("Frozen", category: .movies, points: 3),
    WordEntry("Shrek", category: .movies, points: 3),
    WordEntry("Finding Nemo", category: .movies, points: 3),
    WordEntry("The Mask", category: .movies, points: 3),
    WordEntry("The Matrix", category: .movies, points: 5),
    WordEntry("Joker", category: .movies, points: 5),
    WordEntry("Avengers", category: .movies, points: 5),
    WordEntry("Game of Thrones", category: .movies, points: 5),
    WordEntry("Breaking Bad", category: .movies, points: 5),
    WordEntry("Interstellar", category: .movies, points: 5),
    WordEntry("Squid Game", category: .movies, points: 5),
    WordEntry("Friends", category: .movies, points: 5),
    WordEntry("The Godfather", category: .movies, points: 5),
    WordEntry("Toy Story", category: .movies, points: 5),
    WordEntry("Inception", category: .movies, points: 7),
    WordEntry("Parasite", category: .movies, points: 7),
    WordEntry("Schindler's List", category: .movies, points: 7),
    WordEntry("The Truman Show", category: .movies, points: 7),
    WordEntry("Forrest Gump", category: .movies, points: 7),
    WordEntry("Goodfellas", category: .movies, points: 7),
    WordEntry("Pulp Fiction", category: .movies, points: 7),
    WordEntry("Fight Club", category: .movies, points: 7),
    WordEntry("The Dark Knight", category: .movies, points: 7),
    WordEntry("2001: A Space Odyssey", category: .movies, points: 7),
    // Food
    WordEntry("Pizza", category: .food, points: 3),
    WordEntry("Hamburger", category: .food, points: 3),
    WordEntry("Sushi", category: .food, points: 3),
    WordEntry("Ice cream", category: .food, points: 3),
    WordEntry("Sandwich", category: .food, points: 3),
    WordEntry("Soup", category: .food, points: 3),
    WordEntry("Bread", category: .food, points: 3),
    WordEntry("Pasta", category: .food, points: 3),
    WordEntry("Tacos", category: .food, points: 3),
    WordEntry("Pancakes", category: .food, points: 3),
    WordEntry("Spaghetti", category: .food, points: 5),
    WordEntry("Ramen", category: .food, points: 5),
    WordEntry("Croissant", category: .food, points: 5),
    WordEntry("Baklava", category: .food, points: 5),
    WordEntry("Cotton candy", category: .food, points: 5),
    WordEntry("Doner kebab", category: .food, points: 5),
    WordEntry("Dim sum", category: .food, points: 5),
    WordEntry("Burrito", category: .food, points: 5),
    WordEntry("Churros", category: .food, points: 5),
    WordEntry("Waffles", category: .food, points: 5),
    WordEntry("Fondue", category: .food, points: 7),
    WordEntry("Souffle", category: .food, points: 7),
    WordEntry("Ceviche", category: .food, points: 7),
    WordEntry("Lutefisk", category: .food, points: 7),
    WordEntry("Haggis", category: .food, points: 7),
    WordEntry("Miso soup", category: .food, points: 7),
    WordEntry("Paella", category: .food, points: 7),
    WordEntry("Tiramisu", category: .food, points: 7),
    WordEntry("Beef Wellington", category: .food, points: 7),
    WordEntry("Crepes suzette", category: .food, points: 7),
    // Sports
    WordEntry("Football", category: .sports, points: 3),
    WordEntry("Basketball", category: .sports, points: 3),
    WordEntry("Swimming", category: .sports, points: 3),
    WordEntry("Tennis", category: .sports, points: 3),
    WordEntry("Boxing", category: .sports, points: 3),
    WordEntry("Volleyball", category: .sports, points: 3),
    WordEntry("Running", category: .sports, points: 3),
    WordEntry("Cycling", category: .sports, points: 3),
    WordEntry("Skiing", category: .sports, points: 3),
    WordEntry("Wrestling", category: .sports, points: 3),
    WordEntry("Archery", category: .sports, points: 5),
    WordEntry("Weightlifting", category: .sports, points: 5),
    WordEntry("Horse riding", category: .sports, points: 5),
    WordEntry("Karate", category: .sports, points: 5),
    WordEntry("Gymnastics", category: .sports, points: 5),
    WordEntry("Surfing", category: .sports, points: 5),
    WordEntry("Golf", category: .sports, points: 5),
    WordEntry("Fencing", category: .sports, points: 5),
    WordEntry("Polo", category: .sports, points: 5),
    WordEntry("Table tennis", category: .sports, points: 5),
    WordEntry("Synchronized swimming", category: .sports, points: 7),
    WordEntry("Bungee jumping", category: .sports, points: 7),
    WordEntry("Curling", category: .sports, points: 7),
    WordEntry("Javelin throw", category: .sports, points: 7),
    WordEntry("Skeleton", category: .sports, points: 7),
    WordEntry("Hammer throw", category: .sports, points: 7),
    WordEntry("Rhythmic gymnastics", category: .sports, points: 7),
    WordEntry("Bobsled", category: .sports, points: 7),
    WordEntry("Sumo", category: .sports, points: 7),
    WordEntry("Parkour", category: .sports, points: 7),
    // Everyday Life
    WordEntry("Wedding", category: .everyday, points: 3),
    WordEntry("Hospital", category: .everyday, points: 3),
    WordEntry("Airport", category: .everyday, points: 3),
    WordEntry("Supermarket", category: .everyday, points: 3),
    WordEntry("Traffic jam", category: .everyday, points: 3),
    WordEntry("Birthday party", category: .everyday, points: 3),
    WordEntry("Alarm clock", category: .everyday, points: 3),
    WordEntry("Elevator", category: .everyday, points: 3),
    WordEntry("Queue", category: .everyday, points: 3),
    WordEntry("Library", category: .everyday, points: 3),
    WordEntry("Moving house", category: .everyday, points: 5),
    WordEntry("Power outage", category: .everyday, points: 5),
    WordEntry("Job interview", category: .everyday, points: 5),
    WordEntry("Blind date", category: .everyday, points: 5),
    WordEntry("Surprise party", category: .everyday, points: 5),
    WordEntry("Online shopping", category: .everyday, points: 5),
    WordEntry("Missing bus", category: .everyday, points: 5),
    WordEntry("Parking lot", category: .everyday, points: 5),
    WordEntry("Laundry", category: .everyday, points: 5),
    WordEntry("Stuck in lift", category: .everyday, points: 5),
    WordEntry("IKEA assembly", category: .everyday, points: 7),
    WordEntry("Road rage", category: .everyday, points: 7),
    WordEntry("Social anxiety", category: .everyday, points: 7),
    WordEntry("Ghosting", category: .everyday, points: 7),
    WordEntry("Awkward silence", category: .everyday, points: 7),
    WordEntry("Midlife crisis", category: .everyday, points: 7),
    WordEntry("Video call fail", category: .everyday, points: 7),
    WordEntry("Autocorrect fail", category: .everyday, points: 7),
    WordEntry("Public speaking", category: .everyday, points: 7),
    WordEntry("Passive aggressive", category: .everyday, points: 7),
    // Nature
    WordEntry("Rainbow", category: .nature, points: 3),
    WordEntry("Sunset", category: .nature, points: 3),
    WordEntry("Desert", category: .nature, points: 3),
    WordEntry("Jungle", category: .nature, points: 3),
    WordEntry("Ocean", category: .nature, points: 3),
    WordEntry("Mountain", category: .nature, points: 3),
    WordEntry("River", category: .nature, points: 3),
    WordEntry("Waterfall", category: .nature, points: 3),
    WordEntry("Snow", category: .nature, points: 3),
    WordEntry("Wind", category: .nature, points: 3),
    WordEntry("Tornado", category: .nature, points: 5),
    WordEntry("Snowstorm", category: .nature, points: 5),
    WordEntry("Lightning", category: .nature, points: 5),
    WordEntry("Oasis", category: .nature, points: 5),
    WordEntry("Aurora", category: .nature, points: 5),
    WordEntry("Coral reef", category: .nature, points: 5),
    WordEntry("Eclipse", category: .nature, points: 5),
    WordEntry("Monsoon", category: .nature, points: 5),
    WordEntry("Fog", category: .nature, points: 5),
    WordEntry("Quicksand", category: .nature, points: 5),
    WordEntry("Earthquake", category: .nature, points: 7),
    WordEntry("Volcano", category: .nature, points: 7),
    WordEntry("Avalanche", category: .nature, points: 7),
    WordEntry("Glacier", category: .nature, points: 7),
    WordEntry("Tide", category: .nature, points: 7),
    WordEntry("Black hole", category: .nature, points: 7),
    WordEntry("Drought", category: .nature, points: 7),
    WordEntry("Bioluminescence", category: .nature, points: 7),
    WordEntry("Solar flare", category: .nature, points: 7),
    WordEntry("Permafrost", category: .nature, points: 7),
    // Emotions
    WordEntry("Happiness", category: .emotions, points: 3),
    WordEntry("Fear", category: .emotions, points: 3),
    WordEntry("Anger", category: .emotions, points: 3),
    WordEntry("Sadness", category: .emotions, points: 3),
    WordEntry("Surprise", category: .emotions, points: 3),
    WordEntry("Love", category: .emotions, points: 3),
    WordEntry("Disgust", category: .emotions, points: 3),
    WordEntry("Confusion", category: .emotions, points: 3),
    WordEntry("Excitement", category: .emotions, points: 3),
    WordEntry("Pride", category: .emotions, points: 3),
    WordEntry("Jealousy", category: .emotions, points: 5),
    WordEntry("Embarrassment", category: .emotions, points: 5),
    WordEntry("Boredom", category: .emotions, points: 5),
    WordEntry("Nostalgia", category: .emotions, points: 5),
    WordEntry("Loneliness", category: .emotions, points: 5),
    WordEntry("Relief", category: .emotions, points: 5),
    WordEntry("Guilt", category: .emotions, points: 5),
    WordEntry("Anxiety", category: .emotions, points: 5),
    WordEntry("Envy", category: .emotions, points: 5),
    WordEntry("Gratitude", category: .emotions, points: 5),
    WordEntry("Melancholy", category: .emotions, points: 7),
    WordEntry("Awe", category: .emotions, points: 7),
    WordEntry("Despair", category: .emotions, points: 7),
    WordEntry("Euphoria", category: .emotions, points: 7),
    WordEntry("Betrayal", category: .emotions, points: 7),
    WordEntry("Anticipation", category: .emotions, points: 7),
    WordEntry("Heartbreak", category: .emotions, points: 7),
    WordEntry("Serenity", category: .emotions, points: 7),
    WordEntry("Schadenfreude", category: .emotions, points: 7),
    WordEntry("Homesickness", category: .emotions, points: 7),
    // Famous People
    WordEntry("Charlie Chaplin", category: .famous, points: 3),
    WordEntry("Michael Jackson", category: .famous, points: 3),
    WordEntry("Cristiano Ronaldo", category: .famous, points: 3),
    WordEntry("Einstein", category: .famous, points: 3),
    WordEntry("Napoleon", category: .famous, points: 3),
    WordEntry("Superman", category: .famous, points: 3),
    WordEntry("Santa Claus", category: .famous, points: 3),
    WordEntry("Dracula", category: .famous, points: 3),
    WordEntry("Batman", category: .famous, points: 3),
    WordEntry("Sherlock Holmes", category: .famous, points: 3),
    WordEntry("Cleopatra", category: .famous, points: 5),
    WordEntry("Beyonce", category: .famous, points: 5),
    WordEntry("Bruce Lee", category: .famous, points: 5),
    WordEntry("Freddie Mercury", category: .famous, points: 5),
    WordEntry("Muhammad Ali", category: .famous, points: 5),
    WordEntry("Marilyn Monroe", category: .famous, points: 5),
    WordEntry("James Bond", category: .famous, points: 5),
    WordEntry("Taylor Swift", category: .famous, points: 5),
    WordEntry("Steve Jobs", category: .famous, points: 5),
    WordEntry("Mona Lisa", category: .famous, points: 5),
    WordEntry("Elon Musk", category: .famous, points: 7),
    WordEntry("Leonardo da Vinci", category: .famous, points: 7),
    WordEntry("Oprah Winfrey", category: .famous, points: 7),
    WordEntry("Shakespeare", category: .famous, points: 7),
    WordEntry("Nikola Tesla", category: .famous, points: 7),
    WordEntry("Mahatma Gandhi", category: .famous, points: 7),
    WordEntry("Marie Curie", category: .famous, points: 7),
    WordEntry("Picasso", category: .famous, points: 7),
    WordEntry("Genghis Khan", category: .famous, points: 7),
    WordEntry("Nostradamus", category: .famous, points: 7),
    // Music
    WordEntry("Guitar", category: .music, points: 3),
    WordEntry("Drums", category: .music, points: 3),
    WordEntry("Piano", category: .music, points: 3),
    WordEntry("Singing", category: .music, points: 3),
    WordEntry("Violin", category: .music, points: 3),
    WordEntry("Headphones", category: .music, points: 3),
    WordEntry("Concert", category: .music, points: 3),
    WordEntry("Microphone", category: .music, points: 3),
    WordEntry("Dancing", category: .music, points: 3),
    WordEntry("DJ", category: .music, points: 3),
    WordEntry("Karaoke", category: .music, points: 5),
    WordEntry("Music video", category: .music, points: 5),
    WordEntry("Trumpet", category: .music, points: 5),
    WordEntry("Saxophone", category: .music, points: 5),
    WordEntry("Record player", category: .music, points: 5),
    WordEntry("Air guitar", category: .music, points: 5),
    WordEntry("Choir", category: .music, points: 5),
    WordEntry("Rap battle", category: .music, points: 5),
    WordEntry("Flash mob", category: .music, points: 5),
    WordEntry("Busking", category: .music, points: 5),
    WordEntry("Conducting", category: .music, points: 7),
    WordEntry("Beatboxing", category: .music, points: 7),
    WordEntry("Throat singing", category: .music, points: 7),
    WordEntry("Theremin", category: .music, points: 7),
    WordEntry("Flamenco", category: .music, points: 7),
    WordEntry("Opera singing", category: .music, points: 7),
    WordEntry("Bagpipes", category: .music, points: 7),
    WordEntry("Didgeridoo", category: .music, points: 7),
    WordEntry("Sitar playing", category: .music, points: 7),
    WordEntry("Yodelling", category: .music, points: 7),
    // Places
    WordEntry("Beach", category: .places, points: 3),
    WordEntry("Library", category: .places, points: 3),
    WordEntry("Restaurant", category: .places, points: 3),
    WordEntry("Zoo", category: .places, points: 3),
    WordEntry("Museum", category: .places, points: 3),
    WordEntry("Cinema", category: .places, points: 3),
    WordEntry("Park", category: .places, points: 3),
    WordEntry("Hospital", category: .places, points: 3),
    WordEntry("Gym", category: .places, points: 3),
    WordEntry("School", category: .places, points: 3),
    WordEntry("Amusement park", category: .places, points: 5),
    WordEntry("Opera house", category: .places, points: 5),
    WordEntry("Ice rink", category: .places, points: 5),
    WordEntry("Space station", category: .places, points: 5),
    WordEntry("Haunted house", category: .places, points: 5),
    WordEntry("Casino", category: .places, points: 5),
    WordEntry("Sauna", category: .places, points: 5),
    WordEntry("Prison", category: .places, points: 5),
    WordEntry("Submarine", category: .places, points: 5),
    WordEntry("Observatory", category: .places, points: 5),
    WordEntry("Colosseum", category: .places, points: 7),
    WordEntry("Stonehenge", category: .places, points: 7),
    WordEntry("The Vatican", category: .places, points: 7),
    WordEntry("Area 51", category: .places, points: 7),
    WordEntry("Bermuda Triangle", category: .places, points: 7),
    WordEntry("Machu Picchu", category: .places, points: 7),
    WordEntry("Pompeii", category: .places, points: 7),
    WordEntry("The Louvre", category: .places, points: 7),
    WordEntry("Alcatraz", category: .places, points: 7),
    WordEntry("Chernobyl", category: .places, points: 7),
]
